data:
  tracks_include: ["phylo", 'big_encode', 'fantom']
  train_chrom: []
  test_chrom: [6, 7, 8]
  data_path: "data"
  name: "ukbb"
  window_size_data: 256
  N: 407527
  n_workers: 12
  max_n_snps: 20000
  test_max_n_snps: 5000000
  sumstats_type: all
  drop_nan_beta: true
  beta_inds: 4
  maf_threshold: 0.00001
  use_R_tilde: false
  fix_sumstats_D: false
  use_z: true
  chunk_size: 10
  processed_gen_dir: dense_ld_mats_psd_t0
  ld_dist_thresh: 1000000
  test_ld_dist_thresh: 1000000
  other_args:
      D_as_feature: true

model:
  seed: 11
  eps: 1e-4
  restart: false
  M: 3000000
  include_D: 0.7
  loss: wasp_new
  beta_eval_thresh: 1e-4

architecture:
  model: enformer
  window_size: ${data.window_size_data}
  dim: 1536
  heads: 2
  depth: 2
  target_length: 32
  num_downsamples: ${num_downsampler:${data.window_size_data},${architecture.target_length}}
  n_attention: 1
  average_geno: true
  link: exp
  use_checkpointing: true

train:
  n_epoch: 10
  lr: 0.0001
  lr_sigma: 0.0002
  grad_clip_val: 0.2
  weight_decay: 0
  accumulate: ${data.n_workers}
  scheduler: "default"
  ema: false
  start_log_sigma: 0.
  train_sigma: false
  use_double: true
  train_D: false
  normalize_tracks: false
  tol: 1e-6
  max_iters: 10000
  vtol: 1e-1
  rank_pct: 0.10
  log_every_n_steps: 1

wandb:
  use: true
  project: "fast_gen"
